[package]
name = "rstatus"
version = "0.9.2"
authors = ["Oleg Keri <ezhi99@gmail.com>"]
edition = "2018"

[dependencies]
libc = "*"
time = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"

